<a href="https://colab.research.google.com/github/aarushi-gulati/WEC5BC2-Bank-Marketing-Campaign-Analysis/blob/main/Bank_Analysis_27_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Difference between ordinal and label encoding.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf

In [ ]:
urls = ["https://drive.google.com/file/d/17RbHtm27PJbk_MZ337Gk9wlXaxWY2SJs/view?usp=drive_link", "https://drive.google.com/file/d/17jSJ0lLxsoJ_0jerM71wbhxLW17MSxup/view?usp=drive_link", "https://drive.google.com/file/d/1Lf5_yWIaKA9KRj43C_8rM_1LiSU8gaJr/view?usp=drive_link", "https://drive.google.com/file/d/14VjlhUB0iay9auwVqrIxwBhtrE_7uY-g/view?usp=drive_link", "https://drive.google.com/drive/folders/1etXs4YEsUv9D9XcJbxifn8q8SpzjTm6I"]

bank_full = pd.read_csv('https://drive.google.com/uc?id=' + urls[0].split('/')[-2], delimiter=";")
bank_additional_full = pd.read_csv('https://drive.google.com/uc?id=' + urls[1].split('/')[-2], delimiter=";")
bank = pd.read_csv('https://drive.google.com/uc?id=' + urls[2].split('/')[-2], delimiter=";")
bank_additional = pd.read_csv('https://drive.google.com/uc?id=' + urls[3].split('/')[-2], delimiter=";")
cleaned_bank_additional = pd.read_csv('cleaned_bank_additional_full.csv')

In [ ]:
hot_encoded = pd.get_dummies(bank_additional_full, columns = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome', 'y'])

In [ ]:
hot_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 65 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   age                            41188 non-null  int64  
 1   duration                       41188 non-null  int64  
 2   campaign                       41188 non-null  int64  
 3   pdays                          41188 non-null  int64  
 4   previous                       41188 non-null  int64  
 5   emp.var.rate                   41188 non-null  float64
 6   cons.price.idx                 41188 non-null  float64
 7   cons.conf.idx                  41188 non-null  float64
 8   euribor3m                      41188 non-null  float64
 9   nr.employed                    41188 non-null  float64
 10  job_admin.                     41188 non-null  uint8  
 11  job_blue-collar                41188 non-null  uint8  
 12  job_entrepreneur               41188 non-null 

In [ ]:
hot_encoded = hot_encoded.drop(columns = ['y_no'])

In [ ]:
hot_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 64 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   age                            41188 non-null  int64  
 1   duration                       41188 non-null  int64  
 2   campaign                       41188 non-null  int64  
 3   pdays                          41188 non-null  int64  
 4   previous                       41188 non-null  int64  
 5   emp.var.rate                   41188 non-null  float64
 6   cons.price.idx                 41188 non-null  float64
 7   cons.conf.idx                  41188 non-null  float64
 8   euribor3m                      41188 non-null  float64
 9   nr.employed                    41188 non-null  float64
 10  job_admin.                     41188 non-null  uint8  
 11  job_blue-collar                41188 non-null  uint8  
 12  job_entrepreneur               41188 non-null 

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()

In [ ]:
result = encoder.fit_transform(bank_additional_full)

In [ ]:
print(result)

[[ 39.   3.   1. ... 287.   8.   0.]
 [ 40.   7.   1. ... 287.   8.   0.]
 [ 20.   7.   1. ... 287.   8.   0.]
 ...
 [ 39.   5.   1. ... 171.   0.   0.]
 [ 27.   9.   1. ... 171.   0.   1.]
 [ 57.   5.   1. ... 171.   0.   0.]]


In [ ]:
ordinal_encoding = pd.DataFrame(result, columns=['age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'week', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx','euribor3m', 'nr.employed', 'y'])

In [ ]:
ordinal_encoding.head()

age  job  marital  education  default  housing  loan  contact  month  \
0  39.0  3.0      1.0        0.0      0.0      0.0   0.0      1.0    6.0   
1  40.0  7.0      1.0        3.0      1.0      0.0   0.0      1.0    6.0   
2  20.0  7.0      1.0        3.0      0.0      2.0   0.0      1.0    6.0   
3  23.0  0.0      1.0        1.0      0.0      0.0   0.0      1.0    6.0   
4  39.0  7.0      1.0        3.0      0.0      0.0   2.0      1.0    6.0   

   week  ...  campaign  pdays  previous  poutcome  emp.var.rate  \
0   1.0  ...       0.0   26.0       0.0       1.0           8.0   
1   1.0  ...       0.0   26.0       0.0       1.0           8.0   
2   1.0  ...       0.0   26.0       0.0       1.0           8.0   
3   1.0  ...       0.0   26.0       0.0       1.0           8.0   
4   1.0  ...       0.0   26.0       0.0       1.0           8.0   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed    y  
0            18.0           16.0      287.0          8.0  0.0  
1            18.0           16.0      287.0          8.0  0.0  
2            18.0           16.0      287.0          8.0  0.0  
3            18.0           16.0      287.0          8.0  0.0  
4            18.0           16.0      287.0          8.0  0.0  

[5 rows x 21 columns]

In [ ]:
ordinal_encoding.corrwith(ordinal_encoding["y"])

age               0.030339
job               0.025122
marital           0.046203
education         0.057799
default          -0.099352
housing           0.011552
loan             -0.004909
contact          -0.144773
month            -0.006065
week              0.015967
duration          0.419889
campaign         -0.066532
pdays            -0.320945
previous          0.230181
poutcome          0.129789
emp.var.rate     -0.286833
cons.price.idx   -0.140593
cons.conf.idx     0.069980
euribor3m        -0.368168
nr.employed      -0.355135
y                 1.000000
dtype: float64

In [ ]:
y_hot = hot_encoded['y_yes']
hot_encoded.drop('y_yes', axis = 1, inplace = True)

y_ordinal = ordinal_encoding['y']
ordinal_encoding.drop('y', axis = 1, inplace = True)

In [ ]:
hot_encoded

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0       56       261         1    999         0           1.1          93.994   
1       57       149         1    999         0           1.1          93.994   
2       37       226         1    999         0           1.1          93.994   
3       40       151         1    999         0           1.1          93.994   
4       56       307         1    999         0           1.1          93.994   
...    ...       ...       ...    ...       ...           ...             ...   
41183   73       334         1    999         0          -1.1          94.767   
41184   46       383         1    999         0          -1.1          94.767   
41185   56       189         2    999         0          -1.1          94.767   
41186   44       442         1    999         0          -1.1          94.767   
41187   74       239         3    999         1          -1.1          94.767   

       cons.conf.idx  euribor3m  nr.employed  ...  month_oct  month_sep  \
0              -36.4      4.857       5191.0  ...          0          0   
1              -36.4      4.857       5191.0  ...          0          0   
2              -36.4      4.857       5191.0  ...          0          0   
3              -36.4      4.857       5191.0  ...          0          0   
4              -36.4      4.857       5191.0  ...          0          0   
...              ...        ...          ...  ...        ...        ...   
41183          -50.8      1.028       4963.6  ...          0          0   
41184          -50.8      1.028       4963.6  ...          0          0   
41185          -50.8      1.028       4963.6  ...          0          0   
41186          -50.8      1.028       4963.6  ...          0          0   
41187          -50.8      1.028       4963.6  ...          0          0   

       day_of_week_fri  day_of_week_mon  day_of_week_thu  day_of_week_tue  \
0                    0                1                0                0   
1                    0                1                0                0   
2                    0                1                0                0   
3                    0                1                0                0   
4                    0                1                0                0   
...                ...              ...              ...              ...   
41183                1                0                0                0   
41184                1                0                0                0   
41185                1                0                0                0   
41186                1                0                0                0   
41187                1                0                0                0   

       day_of_week_wed  poutcome_failure  poutcome_nonexistent  \
0                    0                 0                     1   
1                    0                 0                     1   
2                    0                 0                     1   
3                    0                 0                     1   
4                    0                 0                     1   
...                ...               ...                   ...   
41183                0                 0                     1   
41184                0                 0                     1   
41185                0                 0                     1   
41186                0                 0                     1   
41187                0                 1                     0   

       poutcome_success  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
41183                 0  
41184                 0  
41185                 0  
41186                 0  
41187                 0  

[41188 rows x 63 columns]

In [ ]:
x_hot_train, x_hot_test, y_hot_train, y_hot_test = train_test_split(hot_encoded, y_hot, test_size=0.2, random_state=0)

In [ ]:
x_ordinal_train, x_ordinal_test, y_ordinal_train, y_ordinal_test = train_test_split(ordinal_encoding, y_ordinal, test_size=0.2, random_state = 69)

In [ ]:
print(np.shape(x_hot_train))
print(np.shape(x_hot_test))
print(np.shape(y_hot_train))
print(np.shape(y_hot_test))

print(np.shape(x_ordinal_train))
print(np.shape(x_ordinal_test))
print(np.shape(y_ordinal_train))
print(np.shape(y_ordinal_test))

(32950, 63)
(8238, 63)
(32950,)
(8238,)
(32950, 20)
(8238, 20)
(32950,)
(8238,)


In [ ]:
model_hot = Sequential()
model_hot.add(Dense(16, activation = "relu", input_dim = 63))
model_hot.add(Dense(1, activation = "sigmoid"))

In [ ]:
model_ordinal = Sequential()
model_ordinal.add(Dense(16, activation = "relu", input_dim = 20))
model_ordinal.add(Dense(1, activation = "sigmoid"))

In [ ]:
model_hot.compile(loss = "mse", optimizer = "adam", metrics=["accuracy"])

In [ ]:
model_ordinal.compile(loss = "mse", optimizer = "adam", metrics = ['accuracy'])

In [ ]:
model_hot.fit(x_hot_train, y_hot_train, epochs = 5, batch_size=1000)

Epoch 1/5
33/33 [==============================] - 0s 3ms/step - loss: 0.8871 - accuracy: 0.1129
Epoch 2/5
33/33 [==============================] - 0s 2ms/step - loss: 0.8871 - accuracy: 0.1129
Epoch 3/5
33/33 [==============================] - 0s 3ms/step - loss: 0.8871 - accuracy: 0.1129
Epoch 4/5
33/33 [==============================] - 0s 2ms/step - loss: 0.8871 - accuracy: 0.1129
Epoch 5/5
33/33 [==============================] - 0s 2ms/step - loss: 0.8871 - accuracy: 0.1129


In [ ]:
model_ordinal.fit(x_ordinal_train, y_ordinal_train, epochs = 5, batch_size=1000)

Epoch 1/5
33/33 [==============================] - 1s 3ms/step - loss: 0.1122 - accuracy: 0.8878
Epoch 2/5
33/33 [==============================] - 0s 4ms/step - loss: 0.1122 - accuracy: 0.8878
Epoch 3/5
33/33 [==============================] - 0s 4ms/step - loss: 0.1122 - accuracy: 0.8878
Epoch 4/5
33/33 [==============================] - 0s 4ms/step - loss: 0.1122 - accuracy: 0.8878
Epoch 5/5
33/33 [==============================] - 0s 4ms/step - loss: 0.1122 - accuracy: 0.8878


In [ ]:
predictions_hot = model_hot.predict(x_hot_test)

258/258 [==============================] - 0s 1ms/step


In [ ]:
predictions_ordinal = model_ordinal.predict(x_ordinal_test)

258/258 [==============================] - 1s 2ms/step


In [ ]:
loss_and_metrics = model_hot.evaluate(x_hot_test, y_hot_test)
print(loss_and_metrics)
print('Loss = ',loss_and_metrics[0])
print('Accuracy = ',loss_and_metrics[1])

258/258 [==============================] - 1s 1ms/step - loss: 0.8884 - accuracy: 0.1116
[0.8884437680244446, 0.11155620217323303]
Loss =  0.8884437680244446
Accuracy =  0.11155620217323303


In [ ]:
loss_and_metrics = model_ordinal.evaluate(x_ordinal_test, y_ordinal_test)
print(loss_and_metrics)
print('Loss = ',loss_and_metrics[0])
print('Accuracy = ',loss_and_metrics[1])

258/258 [==============================] - 1s 2ms/step - loss: 0.0826 - accuracy: 0.9017
[0.08259719610214233, 0.9016751646995544]
Loss =  0.08259719610214233
Accuracy =  0.9016751646995544


# Clean Data

In [ ]:
cleaned_bank_additional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31204 entries, 0 to 31203
Data columns (total 52 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            31204 non-null  int64  
 1   age                   31204 non-null  int64  
 2   education             31204 non-null  float64
 3   duration              31204 non-null  int64  
 4   campaign              31204 non-null  int64  
 5   pdays                 31204 non-null  int64  
 6   previous              31204 non-null  int64  
 7   emp.var.rate          31204 non-null  float64
 8   cons.price.idx        31204 non-null  float64
 9   cons.conf.idx         31204 non-null  float64
 10  euribor3m             31204 non-null  float64
 11  nr.employed           31204 non-null  float64
 12  job_admin.            31204 non-null  int64  
 13  job_blue-collar       31204 non-null  int64  
 14  job_entrepreneur      31204 non-null  int64  
 15  job_housemaid      

In [ ]:
y_clean = cleaned_bank_additional['y']
cleaned_bank_additional.drop('y', axis = 1, inplace = True)

In [ ]:
x_clean_train, x_clean_test, y_clean_train, y_clean_test = train_test_split(cleaned_bank_additional, y_clean, test_size = 0.2, random_state = 69)

In [ ]:
np.shape(x_clean_train)

(24963, 51)

In [ ]:
model_clean = Sequential()
model_clean.add(Dense(16, activation = "relu", input_dim = 51))
model_clean.add(Dense(1, activation = "sigmoid"))

In [ ]:
model_clean.compile(loss = "mse", metrics = "accuracy", optimizer = "adam")

In [ ]:
model_clean.fit(x_clean_train, y_clean_train, epochs = 10, batch_size = 1000)

Epoch 1/10
25/25 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.9357
Epoch 2/10
25/25 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.9357
Epoch 3/10
25/25 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.9357
Epoch 4/10
25/25 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.9357
Epoch 5/10
25/25 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.9357
Epoch 6/10
25/25 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.9357
Epoch 7/10
25/25 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.9357
Epoch 8/10
25/25 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.9357
Epoch 9/10
25/25 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.9357
Epoch 10/10
25/25 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.9357


In [ ]:
predictions_clean = model_clean.predict(x_clean_test)

196/196 [==============================] - 0s 1ms/step


In [ ]:
loss_and_metrics = model_clean.evaluate(x_clean_test, y_clean_test)
print(loss_and_metrics)
print('Loss = ',loss_and_metrics[0])
print('Accuracy = ',loss_and_metrics[1])

196/196 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.9373
[nan, 0.937349796295166]
Loss =  nan
Accuracy =  0.937349796295166


In [ ]:
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay

In [ ]:
np.shape(predictions_hot)

TensorShape([8238])

In [ ]:
predictions_hot = tf.squeeze(predictions_hot)
l = tf.Variable(predictions_hot).numpy().tolist()
print(l)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
predictions_hot = tf.squeeze(predictions_hot)
l = tf.Variable(predictions_hot).numpy().tolist()
predictions_hot = np.array([1 if x >= 0.5 else 0 for x in predictions_hot])
actual = np.array(y_hot_test)
conf_mat = confusion_matrix(actual, predictions_hot)
displ = ConfusionMatrixDisplay(confusion_matrix=conf_mat)
displ.plot()

TypeError: ignored

In [ ]:
actual = np.array(y_hot_test)
conf_mat = confusion_matrix(actual, predictions_hot)
displ = ConfusionMatrixDisplay(confusion_matrix=conf_mat)
displ.plot()

NameError: ignored